const cats=['Todos','Gamer','Smart Home','Celulares e acessórios','PC e informática','Áudio','Acessórios','Iluminação','Outros'];let selected='Todos', all=[];
const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function imgURL(blob){return blob?URL.createObjectURL(blob):''}
async function load(){all=(await getAll()).filter(p=>p.active);renderCats();render();}
function renderCats(){const el=$('#categories');el.innerHTML=cats.map(c=>`<button class="${c===selected?'active':''}" data-c="${esc(c)}">${c==='Todos'?'✨ ':''}${esc(c)}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.c;renderCats();render();location.hash='produtos';});}
function render(){const term=$('#search').value.toLowerCase();const list=all.filter(p=>(selected==='Todos'||p.category===selected)&&(`${p.name} ${p.description} ${p.category}`).toLowerCase().includes(term));const el=$('#products');$('#empty').classList.toggle('hidden',list.length>0);el.innerHTML=list.map(p=>{const first=p.photos?.[0]?imgURL(p.photos[0]):'';return `<article class="product-card"><div class="product-media">${first?`<img src="${first}" alt="${esc(p.name)}">`:'<div class="no-image">📦</div>'}${p.video?'<span class="video-badge">▶ Vídeo</span>':''}</div><div class="product-body"><span class="product-cat">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description).slice(0,150)}${p.description.length>150?'…':''}</p>${p.price?`<strong class="price">${esc(p.price)}</strong>`:''}<div class="card-actions"><button class="btn secondary details" data-id="${p.id}">Ver detalhes</button><a class="btn primary" href="${esc(p.link)}" target="_blank" rel="noopener noreferrer">Continuar e comprar</a></div></div></article>`}).join('');el.querySelectorAll('.details').forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.id)));}
function openDetail(id){const p=all.find(x=>x.id===id);if(!p)return;const imgs=(p.photos||[]).map(x=>`<img src="${imgURL(x)}" alt="">`).join('');$('#modalContent').innerHTML=`<div class="detail"><div class="detail-gallery">${imgs||'<div class="no-image">📦</div>'}</div><div><span class="product-cat">${esc(p.category)}</span><h2>${esc(p.name)}</h2>${p.price?`<div class="price big">${esc(p.price)}</div>`:''}<p class="detail-desc">${esc(p.description).replace(/\n/g,'<br>')}</p>${p.video?`<video controls src="${imgURL(p.video)}"></video>`:''}<a class="btn primary buy" href="${esc(p.link)}" target="_blank" rel="noopener noreferrer">🛒 Continuar e comprar no Mercado Livre</a></div></div>`;$('#modal').classList.remove('hidden');}
$('#search').oninput=render;$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$('#menu').onclick=()=>$('#nav').classList.toggle('open');
$('#collabForm').onsubmit=e=>{e.preventDefault();$('#formMsg').textContent='Recebido! Em breve entraremos em contato.';e.target.reset()};
$('#aiButton').onclick=()=>$('#chat').classList.toggle('hidden');$('#closeChat').onclick=()=>$('#chat').classList.add('hidden');function chat(){const q=$('#chatInput').value.trim().toLowerCase();if(!q)return;$('#chatBody').innerHTML+=`<div class="user">${esc(q)}</div>`;let a='Posso te ajudar a encontrar produtos por categoria. Experimente dizer: gamer, smart home, celular, áudio ou informática.';if(q.includes('gamer'))a='Na categoria Gamer você encontra periféricos e itens para setup.';else if(q.includes('smart'))a='Na Smart Home ficam produtos para automação e casa inteligente.';else if(q.includes('celular'))a='Temos uma categoria de Celulares e acessórios.';$('#chatBody').innerHTML+=`<div class="bot">${a}</div>`;$('#chatInput').value=''}$('#sendChat').onclick=chat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter')chat()};load();
